export const Serie = {
	m1: { value:  0, name: 'Maternal' },
	m2: { value:  1, name: 'Maternal II' },
	m3: { value:  2, name: 'Maternal III' },
	b1: { value:  3, name: 'Berçário ' },
	b2: { value:  4, name: 'Berçário II' },
	pa: { value:  5, name: 'Pré A' },
	pb: { value:  6, name: 'Pré' },
	f1: { value:  7, name: '1ª serie' },
	f2: { value:  8, name: '2ª serie' },
	f3: { value:  9, name: '3ª serie' },
	f4: { value: 10, name: '4ª serie' },
	f5: { value: 11, name: '5ª serie' },
	f6: { value: 12, name: '6ª serie' },
	f7: { value: 13, name: '7ª serie' },
	f8: { value: 14, name: '8ª serie' },
	e1: { value: 15, name: '1º ano' },
	e2: { value: 16, name: '2º ano' },
	e3: { value: 17, name: '3º ano' }
};
